const playerClubs1 = {
    "Ahmed EL-SHENAWY": ["AL-AHLY"],
    "Alex MERET": ["NAPOLI"],
    "Álex REMIRO": ["REAL SOCIEDAD"],
    "ALISSON Becker": ["LIVERPOOL"],
    "Augusto BATALLA": ["RAYO VALLECANO","RIVER PLATE"],
    "Bernd LENO": ["FULHAM"],
    "David RAYA": ["ARSENAL"],
    "David SORIA": ["GETAFE"],
    "Dean HENDERSON": ["CRYSTAL PALACE"],
    "'DIBU' Martínez": ["ASTON VILLA"],
    "Diogo COSTA": ["PORTO"],
    "Djordje PETROVIĆ": ["STRASBOURG","CHELSEA"],
    "EDERSON De Moraes": ["MANCHESTER CITY"],
    "Finn DAHMEN": ["AUGSBURG"],
    "Franco ARMANI": ["RIVER PLATE"],
    "Gianluigi DONNARUMMA": ["PARIS SAINT-GERMAIN"],
    "Jan OBLAK": ["ATLÉTICO MADRID"],
    "Joan GARCÍA": ["RCD ESPANYOL","FC BARCELONA"],
    "JOHN Victor": ["BOTAFOGO"],
    "Jordan PICKFORD": ["EVERTON"],
    "KEPA Arrizabalaga": ["CHELSEA","ARSENAL"],
    "Lucas CHEVALIER": ["LOSC LILLE","PARIS SAINT-GERMAIN"],
    "Lukáš HORNÍČEK": ["SC BRAGA"],
    "Manuel NEUER": ["BAYERN MÜNCHEN"],
    "Marco CARNESECCHI": ["ATALANTA BC"],
    "Mark FLEKKEN": ["BRENFORD","BAYER LEVERKUSEN"],
    "Matz SELS": ["NOTTINGHAM FOREST"],
    "Mike MAIGNAN": ["AC MILAN"],
    "Mile SVILAR": ["AS ROMA"],
    "Nick POPE": ["NEWCASTLE"],
    "Noah ATUBOLU": ["FREIBURG"],
    "Robert SÁNCHEZ": ["CHELSEA"],
    "Rui SILVA": ["SPORTING CP"],
    "Sergio HERRERA": ["OSASUNA"],
    "Thibaut COURTOIS": ["REAL MADRID"],
    "Unai SIMÓN": ["ATHLETIC CLUB"],
    "Vanja MILINKOVIĆ-SAVIĆ": ["TORINO"],
    "Wojciech SZCZĘSNY": ["FC BARCELONA"],
    "Yann SOMMER": ["INTER MILAN"],
    "Yassine BOUNOU": ["AL HILAL"],

    "Achraf HAKIMI": ["PARIS SAINT-GERMAIN"],
    "Alejandro BALDE": ["FC BARCELONA"],
    "Alessandro BASTONI": ["INTER MILAN"],
    "Alessandro BUONGIORNO": ["NAPOLI"],
    "Alexis SAELEMAEKERS": ["AS ROMA"],
    "Alphonso DAVIES": ["BAYERN MÜNCHEN"],
    "Álvaro CARRERAS": ["BENFICA","REAL MADRID"],
    "Amir RRAHMANI": ["NAPOLI"],
    "Andrei RAŢIU": ["RAYO VALLECANO"],
    "Antonee ROBINSON": ["FULHAM"],
    "Antonio RÜDIGER": ["REAL MADRID"],
    "Dani VIVIAN": ["ATHLETIC CLUB"],
    "Davide ZAPPACOSTA": ["ATALANTA BC"],
    "Dean HUIJSEN": ["BOURNEMOUTH","REAL MADRID"],
    "Denzel DUMFRIES": ["INTER MILAN"],
    "Federico DIMARCO": ["INTER MILAN"],
    "Francisco MOURA": ["PORTO"],
    "GABRIEL Magalhães": ["ARSENAL"],
    "Gonçalo INÁCIO": ["SPORTING CP"],
    "Ibrahima KONATÉ": ["LIVERPOOL"],
    "Iñigo MARTÍNEZ": ["FC BARCELONA","AL-NASSR"], 
    "Jeremie FRIMPONG": ["BAYER LEVERKUSEN","LIVERPOOL"],
    "Josema GIMÉNEZ": ["ATLÉTICO MADRID"],
    "Joško GVARDIOL": ["MANCHESTER CITY"],
    "Jules KOUNDÉ": ["FC BARCELONA"],
    "Jurrien TIMBER": ["ARSENAL"],
    "Leonardo BALERDI": ["OLYMPIQUE MARSEILLE"],
    "Manuel AKANJI": ["MANCHESTER CITY"],
    "Marc GUÉHI": ["CRYSTAL PALACE"],
    "MARQUINHOS Corrêa": ["PARIS SAINT-GERMAIN"],
    "Milos KERKEZ": ["BOURNEMOUTH","LIVERPOOL"],
    "MURILLO Santiago": ["NOTTINGHAM FOREST"],
    "Myles LEWIS-SKELLY": ["ARSENAL"],
    "Nico SCHLOTTERBECK": ["BORUSSIA DORTMUND"],
    "Nicolás OTAMENDI": ["BENFICA"],
    "Nuno MENDES": ["PARIS SAINT-GERMAIN"],
    "Óscar MINGUEZA": ["CELTA VIGO"],
    "Pau CUBARSÍ": ["FC BARCELONA"],
    "Pedro PORRO": ["TOTTENHAM HOTSPUR"],
    "Sergi CARDONA": ["VILLARREAL"],
    "Theo HERNÁNDEZ": ["AC MILAN","AL HILAL"],
    "Thiago SILVA": ["FLUMINENSE"],
    "Virgil VAN DIJK": ["LIVERPOOL"],
    "William SALIBA": ["ARSENAL"],
    "Willian PACHO": ["PARIS SAINT-GERMAIN"],

    "Adrien RABIOT": ["OLYMPIQUE MARSEILLE"],
    "Alex BAENA": ["VILLARREAL","ATLÉTICO MADRID"],
    "Alexis MAC ALLISTER": ["LIVERPOOL"],
    "Andrey SANTOS": ["STRASBOURG","CHELSEA"],
    "Aurélien TCHOUAMÉNI": ["REAL MADRID"],
    "AYOZE Pérez": ["VILLARREAL"],
    "Bernardo SILVA": ["MANCHESTER CITY"],
    "Bruno FERNANDES": ["MANCHESTER UNITED"],
    "Bruno GUIMARÃES": ["NEWCASTLE"],
    "Charles DE KETELAERE": ["ATALANTA BC"],
    "Cole PALMER": ["CHELSEA"],
    "Dani OLMO": ["FC BARCELONA"],
    "Declan RICE": ["ARSENAL"],
    "Dominik SZOBOSZLAI": ["LIVERPOOL"],
    "ÉDERSON José": ["ATALANTA BC"],
    "Eduardo CAMAVINGA": ["REAL MADRID"],
    "Enzo FERNÁNDEZ": ["CHELSEA"],
    "FABIÁN Ruiz": ["PARIS SAINT-GERMAIN"],
    "Fede VALVERDE": ["REAL MADRID"],
    "Florian WIRTZ": ["BAYER LEVERKUSEN","LIVERPOOL"],
    "Frenkie DE JONG": ["FC BARCELONA"],
    "Granit XHAKA": ["BAYER LEVERKUSEN","SUNDERLAND"],
    "Halkan ÇALHANOĞLU": ["INTER MILAN"],
    "'ISCO' Alarcón": ["REAL BETIS"],
    "Jamal MUSIALA": ["BAYERN MÜNCHEN"],
    "João NEVES": ["PARIS SAINT-GERMAIN"],
    "JOHNNY Cardoso": ["REAL BETIS","ATLÉTICO MADRID"],
    "Joshua KIMMICH": ["BAYERN MÜNCHEN"],
    "Jude BELLINGHAM": ["REAL MADRID"],
    "Julian BRANDT": ["BORUSSIA DORTMUND"],
    "Marc CASADÓ": ["FC BARCELONA"], 
    "Marcos LLORENTE": ["ATLÉTICO MADRID"],
    "Martin ØDEGAARD": ["ARSENAL"],
    "Mateo KOVAČIĆ": ["MANCHESTER CITY"], 
    "Mauro ARAMBARRI": ["GETAFE"],
    "Mikel JAUREGIZAR": ["ATHLETIC CLUB"],
    "Moisés CAICEDO": ["CHELSEA"],
    "Morgan ROGERS": ["ASTON VILLA"],
    "Morten HJULMAND": ["SPORTING CP"],
    "Nico PAZ": ["COMO 1907"],
    "Nicolo BARELLA": ["INTER MILAN"],
    "Oihan SANCET": ["ATHLETIC CLUB"],
    "Orkun KÖKÇÜ": ["BENFICA"],
    "Pape GUEYE": ["VILLARREAL"],
    "Patrick BERG": ["FK BODØ/GLIMT"],
    "'PEDRI' González": ["FC BARCELONA"],
    "Rayan CHERKI": ["OLYMPIQUE LYONNAIS","MANCHESTER CITY"],
    "Rodrigo DE PAUL": ["ATLÉTICO MADRID","INTER MIAMI"],
    "Ryan GRAVENBERCH": ["LIVERPOOL"],
    "Scott MCTOMINAY": ["NAPOLI"],
    "Thomas PARTEY": ["ARSENAL","VILLARREAL"],
    "Tijjani REIJNDERS": ["AC MILAN","MANCHESTER CITY"],
    "'VITINHA' Machado": ["PARIS SAINT-GERMAIN"],
    "Xavi SIMONS": ["RB LEIPZIG"],
    "Youri TIELEMANS": ["ASTON VILLA"],
 
    "Ademola LOOKMAN": ["ATALANTA BC"],
    "Alexander ISAK": ["NEWCASTLE"],
    "Alexander SØRLOTH": ["ATLÉTICO MADRID"],
    "AMAD Diallo": ["MANCHESTER UNITED"],
    "Ante BUDIMIR": ["OSASUNA"],
    "Anthony ELANGA": ["NOTTINGHAM FOREST"],
    "Antoine GRIEZMANN": ["ATLÉTICO MADRID"],
    "Bradley BARCOLA": ["PARIS SAINT-GERMAIN"],
    "Brennan JOHNSON": ["TOTTENHAM HOTSPUR"],
    "Bryan MBEUMO": ["BRENTFORD","MANCHESTER UNITED"],
    "Bukayo SAKA": ["ARSENAL"],
    "Chris WOOD": ["NOTTINGHAM FOREST"],
    "Christian PULISIC": ["AC MILAN"],
    "CRISTIANO RONALDO dos Santos": ["AL-NASSR"],
    "Desiré DOUÉ": ["PARIS SAINT-GERMAIN"],
    "Dominik SOLANKE": ["TOTTENHAM HOTSPUR"],
    "Eberechi EZE": ["CRYSTAL PALACE"],
    "Erling HAALAND": ["MANCHESTER CITY"],
    "Ferran TORRES": ["FC BARCELONA"],
    "Harry KANE": ["BAYERN MÜNCHEN"],
    "Heung-min SON": ["TOTTENHAM HOTSPUR","LAFC"],
    "Iñaki WILLAMS": ["ATHLETIC CLUB"],
    "Jacob MURPHY": ["NEWCASTLE"],
    "Jarrod BOWEN": ["WEST HAM"],
    "Jhon ARIAS": ["FLUMINENSE", "WOLVES"],
    "Jonathan DAVID": ["LOSC LILLE","JUVENTUS"],
    "Julián ÁLVAREZ": ["ATLÉTICO MADRID"],
    "Kerem AKTÜRKOĞLU": ["BENFICA"],
    "Khvicha KVARATSKHELIA": ["NAPOLI","PARIS SAINT-GERMAIN"],
    "Kylian MBAPPÉ": ["REAL MADRID"],
    "LAMINE YAMAL Nasraoui": ["FC BARCELONA"],
    "LAUTARO Martínez": ["INTER MILAN"],
    "Lionel MESSI": ["INTER MIAMI"],
    "Luis DÍAZ": ["LIVERPOOL"],
    "Marcus THURAM": ["INTER MILAN"],
    "Mason GREENWOOD": ["OLYMPIQUE MARSEILLE"],
    "Mateo RETEGUI": ["ATALANTA BC"],
    "Matheus CUNHA": ["WOLVES","MANCHESTER UNITED"],
    "Matias SOULÉ": ["AS ROMA"],
    "Mattia ZACCAGNI": ["LAZIO"],
    "Michael OLISE": ["BAYERN MÜNCHEN"],
    "Mohamed SALAH": ["LIVERPOOL"],
    "Moise KEAN": ["FIORENTINA"],
    "Nicholas 'NICO' WILLIAMS": ["ATHLETIC CLUB"],
    "Ollie WATKINS": ["ASTON VILLA"],
    "Omar MARMOUSH": ["EINTRACHT FRANKFURT","MANCHESTER CITY"],
    "Ousmane DEMBÉLÉ": ["PARIS SAINT-GERMAIN"],
    "Paulo DYBALA": ["AS ROMA"],
    "Raoul BELLANOVA": ["ATALANTA BC"],
    "'RAPHINHA' Dias": ["FC BARCELONA"],
    "Robert LEWANDOWSKI": ["FC BARCELONA"],
    "RODRYGO Goes": ["REAL MADRID"],
    "Romelu LUKAKU": ["NAPOLI"],
    "SAMU Aghehowa": ["PORTO"],
    "Serhou GUIRASSY": ["BORUSSIA DORTMUND"],
    "Vangelis PAVLIDIS": ["BENFICA"],
    "Victor OSIMHEN": ["GALATASARAY"],
    "Viktor GYÖKERES": ["SPORTING CP","ARSENAL"],
    "VINÍCIUS Júnior": ["REAL MADRID"],
    "Yoane WISSA": ["BRENTFORD"]
};

export default playerClubs1;