const playerClubs2 = {
    "Adriana NANCLARES": ["ATHLETIC CLUB"],
    "Ann-Katrin BERGER": ["GOTHAM FC"],
    "Anna MOORHOUSE": ["ORLANDO PRIDE"],
    "Aubrey KINGSBURY": ["WASHINGTON SPIRIT"],
    "Ayaka YAMASHITA": ["MANCHESTER CITY"],
    "Cata COLL": ["FC BARCELONA"],
    "Chiamaka NNADOZIE": ["PARIS FC","BRIGHTON"],
    "Christiane ENDLER": ["OL LYONNES"],
    "Daphne VAN DOMSELAAR": ["ARSENAL"],
    "Habiba EMAD SABRY": ["FC MASAR"],
    "Hannah HAMPTON": ["CHELSEA"],
    "Inês PEREIRA": ["DEPORTIVO ABANCA","EVERTON"],
    "Kaelin SHERIDAN": ["SAN DIEGO WAVE"],
    "Khadija ER-RMICHI": ["AS FAR RABAT"],
    "Laura GIULIANI": ["AC MILAN"],
    "Lola GALLARDO": ["ATLÉTICO MADRID"],
    "LORENA Leite": ["GRÊMIO","KANSAS CITY"],
    "Maria Luisa GROHS": ["BAYERN MÜNCHEN"],
    "Misa RODRÍGUEZ": ["REAL MADRID"],
    "Phallon TULLIS-JOYCE": ["MANCHESTER UNITED"],

    "Alexia FERNÁNDEZ": ["GRANADA","ATLÉTICO MADRID"],
    "Casey KRUEGER": ["CHICAGO RED STARS"],
    "Ellie CARPENTER": ["OL LYONNES"],
    "Emily FOX": ["ARSENAL"],
    "Emily SAMS": ["ORLANDO PRIDE"],
    "Esmee BRUGTS": ["FC BARCELONA"],
    "Kaleigh KURTZ": ["NORTH CAROLINA COURAGE"],
    "Leah WILLIAMSON": ["ARSENAL"],
    "Lucy BRONZE": ["CHELSEA"],
    "Maëlle LAKRAR": ["REAL MADRID"],
    "María Pilar 'MAPI' LEÓN": ["FC BARCELONA"],
    "Millie BRIGHT": ["CHELSEA"],
    "Nathalie BJÖRN": ["CHELSEA"],
    "Naomi GIRMA": ["SAN DIEGO WAVE","CHELSEA"],
    "Ona BATLLE": ["FC BARCELONA"],
    "Sakina KARCHAOUI": ["PARIS SAINT-GERMAIN"],
    "Sandy BALTIMORE": ["CHELSEA"],
    "Selma BACHA": ["OL LYONNES"],
    "Steph CATLEY": ["ARSENAL"],
    "Tara ELIMBI GILBERT": ["PARIS SAINT-GERMAIN"],
    "Vanessa GILLES": ["OL LYONNES","BAYERN MÜNCHEN"],
    "Wendie RENARD": ["OL LYONNES"],

    "AITANA Bonmatí": ["FC BARCELONA"],
    "ALEXIA Putellas": ["FC BARCELONA"],
    "Caroline WEIR": ["REAL MADRID"],
    "Claire LAVOGEZ": ["REAL SOCIEDAD"],
    "Clàudia PINA": ["FC BARCELONA"],
    "Damaris EGURROLA": ["OL LYONNES"],
    "'DEBINHA Miri'": ["KANSAS CITY CURRENT"],
    "Frida MAANUM": ["ARSENAL"],
    "Grace CLINTON": ["MANCHESTER UNITED"],
    "Grace GEYORO": ["PARIS SAINT-GERMAIN"],
    "Hal HERSHFELT": ["WASHINGTON SPIRIT"],
    "Johanna KANERYD": ["CHELSEA"],
    "Jule BRAND": ["WOLFSBURG","OL LYONNES"],
    "Katie MCCABE": ["ARSENAL"],
    "Katrina GORRY": ["WEST HAM"],
    "Keira WALSH": ["FC BARCELONA","CHELSEA"],
    "Kim LITTLE": ["ARSENAL"],
    "'KIKA' Nazareth": ["FC BARCELONA"],
    "Lauren JAMES": ["CHELSEA"],
    "Lindsey HEAPS (Horan)": ["OL LYONNES"],
    "Lo'eau LABONTA": ["KANSAS CITY CURRENT"],
    "MARIONA Caldentey": ["ARSENAL"],
    "MARTA Vieira": ["ORLANDO PRIDE"],
    "Melchie DUMORNAY": ["OL LYONNES"],
    "'PATRI' Guijarro": ["FC BARCELONA"],
    "Pernille HARDER": ["BAYERN MÜNCHEN"],
    "Sandie TOLETTI": ["REAL MADRID"],
    "Vanessa DIBERNARDO": ["KANSAS CITY CURRENT"],
    "VICKY López": ["FC BARCELONA"],

    "Alba REDONDO": ["REAL MADRID"],
    "Alessia RUSSO": ["ARSENAL"],
    "Alyssa THOMPSON": ["ANGEL CITY"],
    "Amanda GUTIERRES": ["PALMEIRAS"],
    "Barbra BANDA": ["ORLANDO PRIDE"],
    "Caroline GRAHAM HANSEN": ["FC BARCELONA"],
    "Chloe KELLY": ["MANCHESTER CITY","ARSENAL"],
    "Clara MATEO": ["PARIS FC"],
    "Cristiana GIRELLI": ["JUVENTUS"],
    "Cristina MARTÍN-PRIETO": ["BENFICA"],
    "Delphine CASCARINO": ["SAN DIEGO WAVE"],
    "Edna IMADE": ["GRANADA"],
    "ESTHER González": ["GOTHAM FC"],
    "Ewa PAJOR": ["FC BARCELONA"],
    "Guro REITEN": ["CHELSEA"],
    "Kadidiatou DIANI": ["OL LYONNES"],
    "Khadija SHAW": ["MANCHESTER CITY"],
    "Klara BÜHL": ["BAYERN MÜNCHEN"],
    "Laura FREIGANG": ["EINTRACHT FRANKFURT"],
    "Lineth BEERENSTEYN": ["WOLFSBURG"],
    "Linda CAICEDO": ["REAL MADRID"],
    "Mary FOWLER": ["MANCHESTER CITY"],
    "Olivia SMITH": ["LIVERPOOL","ARSENAL"],
    "Signe BRUUN": ["REAL MADRID"],
    "Sofia CANTORE": ["JUVENTUS","WASHINGTON SPIRIT"],
    "Sophia WILSON (Smith)": ["PORTLAND THORNS"],
    "Stina BLACKSTENIUS": ["ARSENAL"],
    "Sveindís JÓNSDÓTTIR": ["WOLFSBURG","ANGEL CITY"],
    "Tabitha CHAWINGA": ["OL LYONNES"],
    "Trinity RODMAN": ["WASHINGTON SPIRIT"]
};

export default playerClubs2;